---
title: "Analysis"
author: "Stijn van den Broek"
date: "02/05/2021"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(corrplot)
library(broom)
```

## Reading the data

```{r}
data = read.csv('diabetes.csv')
```

## Setting the seed

```{r}
set.seed(123)
```

## 1. formulating an analysis model

```{r}
analysis_model = function(data, print = FALSE, synthetic = FALSE) {

  analyse_dataframe = function(model) { #function for getting the coefficients of the data in a list
    coefficient_row = rep(NA, 0)
    for (i in seq(1, nrow(tidy(model)), 1)) {
      row = tidy(model)[i,]
      names(row) = paste0(row$term, '_', names(row))
      row = row[-1]
      coefficient_row = c(coefficient_row, row)
    }
   
    if (print == TRUE) {
      print(summary(model))
    }
    
    return(coefficient_row)
  }

  if (synthetic == TRUE) {
    coefficient_dataframe = data.frame()
    nsim = 1
    for (x in seq(1, length(data), 1)) {
      m = 1
      imputations = data[[x]]
      for (n in seq(1, imputations$m, 1)) {
        synth_data = complete(imputations, action = n)
        synthetic_model = glm(Outcome~Pregnancies+Glucose+BloodPressure+SkinThickness+Insulin+BMI+DiabetesPedigreeFunction+Age, data = synth_data, family = "binomial") #very clunky implementation, but it works for now.
        synthetic_coefficients = analyse_dataframe(synthetic_model)
        synthetic_coefficients = synthetic_coefficients %>% 
          c(nsim) %>% 
          c(m) %>% 
          data.frame()
        names(synthetic_coefficients)[(ncol(synthetic_coefficients)-1)] = "nsim"
        names(synthetic_coefficients)[ncol(synthetic_coefficients)] = "m"
        synthetic_coefficients = cbind(synthetic_coefficients, statistical_properties(synth_data, print = FALSE)) #adding the statistical properties of the data
        coefficient_dataframe = rbind(coefficient_dataframe, synthetic_coefficients)
        m = m+1
      }
      nsim = nsim+1
    }
  }
  
  else {
    model = glm(Outcome~Pregnancies+Glucose+BloodPressure+SkinThickness+Insulin+BMI+DiabetesPedigreeFunction+Age, data = data, family = "binomial") #also clunky.
    coefficient_dataframe = data.frame(analyse_dataframe(model))
    coefficient_dataframe = cbind(coefficient_dataframe, statistical_properties(data, print = FALSE)) #adding the statistical properties of the data
  }
  
  return(coefficient_dataframe)
}
```

## Function for obtaining statistical properties

```{r}
statistical_properties = function(dataframe, print = TRUE) {
  
  make_wide_columns = function(list, statistic) {
    statistic_columns = data.frame(placeholder = NA)
    for (i in seq(1, length(list), 1)) {
      column_name = paste0(names(list)[i], '_', statistic)
      value = list[i]
      single_column = data.frame(placeholder = value)
      colnames(single_column) = column_name
      statistic_columns = cbind(statistic_columns, single_column)
    }
    
    statistic_columns = statistic_columns[,-1]
    return(statistic_columns)
  }
  
  mean = lapply(dataframe, mean, na.rm = TRUE)
  variance = apply(dataframe, 2, var)
  standard_deviation = apply(dataframe, 2, sd)
  
  if (print == TRUE) {
    print(corrplot(cor(dataframe), method = "color"))
  }
  
  meancols = make_wide_columns(mean, "mean")
  varcols = make_wide_columns(variance, "var")
  sdcols = make_wide_columns(standard_deviation, "sd")
  
  statistics = cbind(meancols, varcols, sdcols)
  
  return(statistics)
}
```

```{r}
make_wide_columns = function(list, statistic) {
  statistic_columns = data.frame(placeholder = NA)
  for (i in seq(1, length(list), 1)) {
    column_name = paste0(names(list)[i], '_', statistic)
    value = list[i]
    single_column = data.frame(placeholder = value)
    colnames(single_column) = column_name
    statistic_columns = cbind(statistic_columns, single_column)
  }
  
  statistic_columns = statistic_columns[,-1]
  return(statistic_columns)
}
```

## Function for plotting distributions

```{r}
dataset_distribution = function(dataframe, bins = 20) {
  ggplot(gather(dataframe), aes(value)) + 
    geom_histogram(bins = bins) + 
    facet_wrap(~key, scales = 'free_x')
}
```

## 2. Running the analysis model on the data set to obtain the true data inference

```{r}
analysis = analysis_model(data = data, print = FALSE, synthetic = FALSE)
```

## 3. Obtaining the statistical properties of the true data set

```{r}
true_statistics = statistical_properties(data)
```

## 4. Plotting the distributions of the true data set

```{r}
dataset_distribution(data)
```
