---
title: "Simulation_CIC_Mirthe"
author: "Mirthe Hendriks"
date: "14-5-2021"
output: html_document
---

```{r}
library(mice) #imputations
library(readr)

library(magrittr) # piping 
library(dplyr) #data manipulation
library(furrr) #parallel mapping
library(corrplot)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(broom)
library(purrr)
library(caret)
library(mboost) # for prediction model with method glmboost for classification 
library(DT)

set.seed(123) #seed for reproducibility 

```

Read data
```{r}
setwd("~/ADS/Thesis")
truedata <- read_csv("diabetes.csv", 
                 col_types = cols(Pregnancies = col_integer(), 
                                  Glucose = col_integer(), 
                                  BloodPressure = col_integer(), 
                                  SkinThickness = col_integer(), 
                                  Insulin = col_integer(), 
                                  Age = col_integer(), 
                                  Outcome = col_factor(levels = c("1", "0"))))

truedata <- truedata[!truedata$BMI == 0,] #disregard data with BMI of 0 
truedata <- truedata[!truedata$BloodPressure == 0,] #disregard data with BloodPressure of 0

print(truedata)
```

```{r}
#looking at the data 
summary(truedata)
dim(truedata)
str(truedata)
```
```{r}
#complete model; logistic regression, all variables included
model1<-glm(Outcome~Pregnancies+Glucose+BloodPressure+SkinThickness+Insulin+BMI+DiabetesPedigreeFunction+Age, data=truedata, family = binomial(link = "logit"))
summary(model1)
```
# Analysis Model 
```{r}
### Formulate an analysis model 

#model: logistic regression, three selected predictors 
model_true<-glm(Outcome~BMI+Glucose+Pregnancies, data=truedata, family=binomial(link = "logit"))
summary(model_true)
confint(model_true)

#logistic regression model shortened 
model<-function(x){ 
  glm(Outcome~BMI+Glucose+Pregnancies, data=x, family=binomial(link = "logit"))
}
```
### Statistical properties
```{r}

#obtain the statistical properties of the observed data 
stat_properties<-function(x){ 
  mu_preg<-mean(x$Pregnancies)
  mu_gluc<-mean(x$Glucose)
  mu_BMI<-mean(x$BMI)
  var_preg <- var(x$Pregnancies)
  var_gluc <- var(x$Glucose)
  var_BMI <- var(x$BMI)
  beta_preg <- x %>% model %>% coefficients %>% .[2]
  beta_gluc <- x %>% model %>% coefficients %>% .[3]
  beta_BMI <- x %>% model %>% coefficients %>% .[4]
  resvar <- x %>% model %>% residuals %>% var
  R2 <- x %>% model %>% summary %>% .$r.squared
  return(unlist(c(mu_preg,mu_gluc,mu_BMI,var_preg,var_gluc,var_BMI,beta_preg,beta_gluc,beta_BMI,resvar,R2)))
}

#correlation variables 
truedata_num<- data.frame(lapply(truedata, function(x) as.numeric(as.character(x))))
cor(truedata_num)
corrplot(cor(truedata_num))

#plot distributions of all observed variables 
distributions <- function(x){
  ggplot(gather(x),aes(value))+
    geom_histogram(bins=10)+
    facet_wrap(~key, scales = 'free_x')
}


#plot the distributions of the analysis model variables 
distributions_model<-function(x){ 
  hist_preg <- hist(x$Pregnancies)
  hist_gluc <- hist(x$Glucose)
  hist_BMI <- hist(x$BMI)
}

stat_properties(truedata)
distributions_model(truedata)
distributions(truedata_num)

```

# Simulation

### Specify method
```{r}
#specify method 
meth <- make.method(truedata)
meth <- rep("pmm",ncol(truedata))  
names(meth) <- colnames(truedata)
meth['Outcome'] <- "logreg"
#default synthetic datasets; method specified as pmm and logreg for the binary outcome variable

#cart method, all variables are imputed by means of cart (classification and regression trees)
cart <- rep("cart", ncol(truedata))
names(cart) <- colnames(truedata)

#specify predictor matrix 
pred <- make.predictorMatrix(truedata)
```

```{r}
#parallel processing for an increased speed
plan(multisession)
nsim=1000 #number of iterations, later change to 1000 
```


### Generate synthetic data different methods
```{r}

# syn_ds <- future_map(1:nsim, ~ { 
#   truedata %>% mice(m=5,
#                     method = meth,
#                     predictorMatrix = pred,
#                     where=matrix(TRUE, nrow(truedata), ncol(truedata)),
#                     print=FALSE)
# }, .options=future_options(seed=as.integer(123)), .progress=TRUE, .id = "syn")
# 
# #set seed again in future_options to ensure reproducible results with parallel processing 
# 
# #make synthetic datasets using cart stats method 
# syn_cart <- future_map(1:nsim, ~ { 
#   truedata %>% mice(m=5,
#                     method = cart,
#                     predictorMatrix = pred,
#                     where=matrix(TRUE, nrow(truedata), ncol(truedata)),
#                     print=FALSE)
# }, .options=future_options(seed=as.integer(123)), .progress=T, .id = "syn")
# 
# syn_cart_maxit <- future_map(1:nsim, ~ { 
#   truedata %>% mice(m = 5,
#                     maxit = 1,
#                     method = cart,
#                     predictorMatrix = pred,
#                     where = matrix(TRUE, nrow(truedata), ncol(truedata)),
#                     print = FALSE)
# }, .options=future_options(seed=as.integer(123)), .progress=T, .id = "syn")
# 
# syn_cartcp <- future_map(1:nsim, ~ { 
#   truedata %>% mice(m = 5,
#                     method = cart,
#                     predictorMatrix = pred,
#                     where = matrix(TRUE, nrow(truedata), ncol(truedata)),
#                     cp = 1e-32,
#                     minbucket = 3,
#                     print = FALSE)
# }, .options=future_options(seed=as.integer(123)), .progress=T, .id = "syn")
# 
# syn_cartcp_maxit <- future_map(1:nsim, ~ { 
#   truedata %>% mice(m = 5,
#                     maxit = 1,
#                     method = cart,
#                     predictorMatrix = pred,
#                     where = matrix(TRUE, nrow(truedata), ncol(truedata)),
#                     cp = 1e-32,
#                     minbucket = 3,
#                     print = FALSE)
# }, .options=future_options(seed=as.integer(123)), .progress=T, .id = "syn")
```


```{r}
syn_ds <- readRDS('syn_ds_model.rds')
syn_cart <- readRDS('syn_cartt_model.rds')
syn_cart_maxit <- readRDS('syn_cart_maxit.rds')
syn_cartcp <- readRDS('syn_cartcp.rds')
syn_cartcp_maxit <- readRDS('syn_cartcp_maxit.rds')

```


### Pooling 
```{r}
# pool function partially synthetic data
pool3.syn <- function(mira) {
  if(class(mira)[1] == "mira") { # if the input object is of class mira
    fitlist <- mira %$% analyses # extract the analyses from the mira object
  } 
  else {
    fitlist <- mira              # and otherwise, just take the input list
  }
  
  vars <- fitlist[[1]] %>% coef() %>% names()

  m <- length(fitlist)           # number of imputations
  
  pooled <- fitlist %>% 
    map_dfr(broom::tidy) %>%
    group_by(term) %>%
    summarise(est     = mean(estimate),
              bm      = sum((estimate - est)^2) / (m - 1),
              ubar    = mean(std.error^2),
              var     = ubar + bm/m, # new variance estimate
              df      = (m - 1) * (1 + (ubar * m)/bm), # and new df estimate
              lower   = est - qt(.975, df) * sqrt(var),
              upper   = est + qt(.975, df) * sqrt(var), .groups = 'drop') %>% 
    arrange(factor(term, levels=vars)) #order rows by values of selected columns 
  pooled
}

#pools the m=5 iterations for the 1000 simulations 

```

```{r}
#Pool various synthetic datasets

#outputs a tibble of 4000 x 8 with the pooled parameter estimates for the 1000 simulations;
# an intercept and three regression coefficients (BMI, Glucose, Pregnancies)

pooled_ds <- map_dfr(syn_ds, function(x) {
  x %$%
    glm(Outcome ~ BMI + Glucose + Pregnancies, family = binomial(link = "logit")) %>% 
    pool3.syn()
})


pooled_cart <- map_dfr(syn_cart, function(x) {
  x %$%
    glm(Outcome ~ BMI + Glucose + Pregnancies, family = binomial(link = "logit")) %>% 
    pool3.syn()
})

pooled_cart_maxit <- map_dfr(syn_cart_maxit, function(x) {
  x %$%
    glm(Outcome ~ BMI + Glucose + Pregnancies, family = binomial(link = "logit")) %>% 
    pool3.syn()
})

pooled_cartcp <- map_dfr(syn_cartcp, function(x) {
  x %$%
    glm(Outcome ~ BMI + Glucose + Pregnancies, family = binomial(link = "logit")) %>% 
    pool3.syn()
})

pooled_cartcp_maxit <- map_dfr(syn_cartcp_maxit, function(x) {
  x %$%
    glm(Outcome ~ BMI + Glucose + Pregnancies, family = binomial(link = "logit")) %>% 
    pool3.syn()
})

pooled_ds
pooled_cart
pooled_cart_maxit
pooled_cartcp
pooled_cartcp_maxit
```

# Evaluation; CIC
```{r}
#Function confidence interval coverage 
ci_cov <- function(pooled, true_fit = NULL, coefs = NULL, vars = NULL) {
  
  if (!is.null(true_fit)) {
    coefs <- coef(true_fit)
    vars   <- diag(vcov(true_fit))
  }
 
  nsim <- nrow(pooled) / length(unique(pooled$term))
  
  pooled %>% mutate(true_coef = rep(coefs, times = nsim),
                    true_var  = rep(vars, times = nsim),
                    cover     = lower < true_coef & true_coef < upper) %>%
    group_by(term) %>%
    summarise("True Est" = unique(true_coef),
              "Syn Est"  = mean(est),
              "Bias"     = mean(est - true_coef),
              "True SE"  = unique(sqrt(true_var)),
              "Syn SE"   = mean(sqrt(var)),
              "df"       = mean(df),
              "Lower"    = mean(lower),
              "Upper"    = mean(upper),
              "CIW"      = mean(upper - lower),
              "Coverage" = mean(cover), .groups = "drop")
}

```

```{r}
cic_ds <- ci_cov(pooled_ds, true_fit = model_true)
cic_cart <- ci_cov(pooled_cart, true_fit = model_true)
cic_cart_maxit <- ci_cov(pooled_cart_maxit, true_fit = model_true)
cic_cartcp <- ci_cov(pooled_cartcp, true_fit = model_true)
cic_cartcp_maxit <- ci_cov(pooled_cartcp_maxit, true_fit = model_true)

column_names= c('True Est', 'Syn Est', 'Bias', 'True SE','Syn SE', 'df', 'Lower', 'Upper', 'CIW', 'Coverage')

datatable(cic_ds) %>% formatRound(columns = column_names,digits=3)
datatable(cic_cart) %>% formatRound(columns = column_names,digits=3)
datatable(cic_cart_maxit) %>% formatRound(columns = column_names,digits=3)
datatable(cic_cartcp) %>% formatRound(columns = column_names,digits=3)
datatable(cic_cartcp_maxit) %>% formatRound(columns = column_names,digits=3)

```



```{r}
#checking the distribution of the parameters
ggplot(data = pooled_cart, aes(est)) + geom_histogram(bins=25) + facet_wrap(~term, scales = 'free_x')
```

