---
title: "Synthesis"
author: "Stijn van den Broek"
date: "02/05/2021"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(magrittr)
library(mice)
library(furrr)
library(purrr)
library(broom.mixed)
```

## Reading the data

```{r}
data = read.csv('diabetes.csv')
data[,'Outcome'] = factor(data[,'Outcome'])
```

## Synthesizing function and imputation methods

```{r}
cart = rep("cart", ncol(data))
names(cart) = colnames(data)

custom_method = c("cart", "pmm", "pmm", "pmm", "cart", "pmm", "cart", "cart", "logreg")
names(custom_method) = colnames(data)


synthesize = function(dataframe, method = custom_method, m = 5, nsim = 100) {
  method = method
  predict <- make.predictorMatrix(dataframe)
  syn = future_map(1:nsim, ~ { 
  dataframe %>% mice(m=m,
                    method = method,
                    predictorMatrix = predict,
                    where=matrix(TRUE, nrow(dataframe), ncol(dataframe)),
                    print=FALSE)
  }, .options=future_options(seed=as.integer(123)), .progress=T, .id = "syn")
  
  return(syn)
}
```

## Pooling function

```{r}
pool3.syn = function(mira) {
  
  if(class(mira)[1] == "mira") { # if the input object is of class mira
    fitlist <- mira %$% analyses # extract the analyses from the mira object
  }
  else {
    fitlist <- mira              # and otherwise, just take the input list
  }
  
  m <- length(fitlist)           # number of imputations
  
  pooled <- fitlist %>% 
    map_dfr(broom::tidy) %>%
    group_by(term) %>%
    summarise(est     = mean(estimate),
              bm      = sum((estimate - est)^2) / (m - 1),
              ubar    = mean(std.error^2),
              var     = ubar + bm/m, # new variance estimate
              df      = (m - 1) * (1 + (ubar * m)/bm), # and new df estimate
              lower   = est - qt(.975, df) * sqrt(var),
              upper   = est + qt(.975, df) * sqrt(var), .groups = 'drop')
  
  return(pooled)
}
```

## Confidence interval function

```{r}
ci_cov = function(pooled, true_fit = NULL, coefs = NULL, vars = NULL) {
  
  if (!is.null(true_fit)) {
    coefs = coef(true_fit)
    vars = diag(vcov(true_fit))
  }
  
  nsim = nrow(pooled) / length(coefs)
  
  pooled %>% mutate(true_coef = rep(coefs, nsim),
                    true_var  = rep(vars, nsim),
                    cover     = lower < true_coef & true_coef < upper) %>%
    group_by(term) %>%
    summarise("True Est" = unique(true_coef),
              "Syn Est"  = mean(est),
              "Bias"     = mean(est - true_coef),
              "True SE"  = unique(sqrt(true_var)),
              "Syn SE"   = mean(sqrt(var)),
              "df"       = mean(df),
              "Lower"    = mean(lower),
              "Upper"    = mean(upper),
              "CIW"      = mean(upper - lower),
              "Coverage" = mean(cover), .groups = "drop")
}
```

## 5a. Synthesizing the data

```{r}
synthesized = synthesize(data, nsim = 10)
```

## 5c. Running the analysis model on each of the synthetic sets

```{r}
synthetic_analysis = analysis_model(data = synthesized, print = FALSE, synthetic = TRUE) #function is found in Analysis_Stijn.rmd
```

## 5g. Pooling the model parameters over the sets and recording the accuracy
```{r}
pooled = map_dfr(synthesized, function(x) {
  x %$%
  glm(Outcome ~ Pregnancies + Glucose, family = 'binomial') %>%
  pool3.syn()
})
```

## 6??
```{r}
true_model = glm(Outcome~Pregnancies+Glucose, data = data, family = "binomial")
confidence_interval = ci_cov(pooled, true_fit = true_model)
```
